# -*- coding: utf-8 -*-
"""sentence.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19g6sQMgLXN19k7Yo_BYOT6VllyUwPeuV
"""

!pip install sentence_transformers

from sentence_transformers import SentenceTransformer,util
#Load the model
model=SentenceTransformer('all-MiniLM-L6-V2')
#Take input from user
text1=input("Enter text1: ")
text2=input("Enter text2: ")
#convert text to embeddings
embedding1=model.encode(text1)
embedding2=model.encode(text2)
#calculate similarity
similarity=util.cos_sim(embedding1,embedding2)
#show result
print("\n Similarity Score:",round(float(similarity),2))
if similarity>0.75:
  print("Similarity level:High")
elif similarity>0.4:
  print("Similarity level:Medium")
else :
  print("Similarity level:Low")